### ISSUE TITLE
support get_conv

### ISSUE THREAD

**Issue by carnott-snap** [rcatolino/pam_sm_rust#13]
Currently, interactions with the user can happen via `get_authtok`, unfortunately I have need to do more, something that is only exposed via [`PamConv`](https://github.com/rcatolino/pam_sm_rust/blob/master/src/pam_types.rs#L62). [Other libraries](https://github.com/anowell/pam-rs/blob/master/pam-http/src/lib.rs#L53) expose this as an interface, could `pamsm`?

**Comment by rcatolino** [comment]
I could definitely add support for it. I've never used it though, so I'm not sure what the best api would be. I'm thinking of adding the following method to ```Pam``` : 
```
fn conv(&self, messages: &[Message]) -> PamResult<Vec<CString>>;
```
With a ```Message``` defined as :
```
pub struct Message {
    pub style: PamMsgStyle,
    pub msg: String,
}
```
So you could call the conv callback like that :
```
let msg1 = Message {
  style: PamMsgStyle::PROMPT_ECHO_ON,
  msg: String::from("password goes here")
};
let result = match pamh.conv(&[msg1]) {
  Ok(r) => // do something with the responses
  Err(e) => // do something with the error
};
```
This seems a little heavy if most use cases only involve passing one message as he man page for ```pam_conv``` suggests.
Then a simple ```fn conv(&self, message: &str, style: PamMsgStyle) -> PamResult<&CStr>``` would be enough, no need to define any new structs at all.  Do you need to send multiple messages at once ?

**Comment by urandom2** [comment]
Glad to see we are on the same page; you conjured about the interface that I PoCed last night.

My usecase does not need multiple messages, and I think that for now we can just tell people to call `conv` multiple times.

I would advise using this structure, since iirc the message is optional and `pamh.conv("")` looks weird:
```rust
fn conv(&self, prompt: Option<&str>, style: PamMsgStyle) -> PamResult<&CStr>;
```

**Comment by rcatolino** [comment]
We can go with the simple version then. And we can always add a ```conv_many``` allowing multiple messages later if somebody needs it.
Are you working on an implementation ?

**Comment by urandom2** [comment]
Awesome, I like that direction. Let me open a pr with the work I have done.

**Comment by carnott-snap** [comment]
When are you planning to cut the release with this feature?

**Comment by rcatolino** [comment]
I have published a new release with your changes. No point in waiting for a release.
