### ISSUE TITLE
Support setting env

### ISSUE THREAD

**Issue by kuon** [rcatolino/pam_sm_rust#19]
I use your library for my PAM module, but I need to be able to set env vars.

Currently, `pam_putenv` is not exposed, it would be great if it could. `pam_getenv` would be a bonus.

It's a minor change, so I guess it would be quicker for your to add it, but if you don't have the time, I'll gladly make a PR.

**Comment by rcatolino** [comment]
I've implemented putenv and getenv in #20 Can you try it out ?

**Comment by kuon** [comment]
@rcatolino I tried #20 and it seems to work fine.
