### ISSUE TITLE
Support cleanup() callback

### ISSUE THREAD

**Issue by Natureshadow** [rcatolino/pam_sm_rust#23]
Alongside #22, please also allow implementations to override the `cleanup()` callback.

**Comment by lucab** [comment]
This only refers to the last parameter of `pam_set_data`, right? In which case I think it's enough to keep #22 only and just note there that it should take some kind of `Option<CleanupFn>`.

**Comment by Natureshadow** [comment]
I'm not sure. Reading the docs of `pam_set_data`, I think you are right. Reading the docs of `pam_end`, it suggest that a function called `cleanup` is always called. However, as it is not even namespaced, the `pam_end` manual is written in a confusing way, or I hold the manual wrong.

**Comment by rcatolino** [comment]
I've started to do some tests on the `set_get_data` branch. My tests suggests the cleanup function is associated with the data name used as the second argument to `pam_set_data` and is called once for each call to `pam_set_data`, either when `pam_end` is called or when `pam_set_data` is called again with the same name.

As such I agree with @lucab , the cleanup is necessary to implement as part of `pam_set_data` api and makes little sense without it, there's no need for a second issue to track this, so I'm closing this one for now.
