### ISSUE TITLE
invalid return value

### ISSUE THREAD

**Issue by momiji** [rcatolino/pam_sm_rust#27]
Hi, I think I found an issue, but... as I'm only doing rust since a few days, I may be completely wrong.

I'm basicaly porting a golang pam authentication module to rust because of some unknown issues (maybe due to GC), and I couldn't get my code working until I realize that the return value pamError might not work as expected.

Let me try to explain a bit more...

**1. how it works**

Pam configuration (password-auth and system-auth):
```
...
auth        requisite      /lib64/security/pam_safe/pam_safe.so first_pass
auth        sufficient     /lib64/security/pam_safe/pam_safe.so second_pass
auth        sufficient    pam_unix.so nullok try_first_pass
...
```

The idea is:
- if users are not managed by the module, requisite returns success then sufficient returns error, forcing the other modules to run (like pam_unix with default password authentication, ...)
- if users are managed by the module, requisite returns success if password is valid then sufficient returns success, preventing pam_unix from running

**2. small prototype**

When reducing the code to the smallest as possible hardcoding only the unmanaged use-case, pam is not working as expected as pam_unix is not validating the password for un-managed users. Password should be checked by pam_unix, as requisite returns success and sufficient returns error, but it is never the case.

```rust
impl PamServiceModule for PamSafe {
    fn setcred(_: Pam, _: PamFlags, _: Vec<String>) -> PamError {
        PamError::SUCCESS
    }

    fn authenticate(pamh: Pam, flags: PamFlags, args: Vec<String>) -> PamError {
        for a in args {
            match a.as_str() {
                "first_pass" => {
                    pinfo!("first pass");
                    return PamError::SUCCESS
                }
                "second_pass" => {
                    pinfo!("second pass");
                    return PamError::AUTH_ERR
                }
                _ => {}
            }
        }
        pinfo!("service error");
        PamError::SERVICE_ERR
    }
}
```

**3. changing the macro**

As I couldn't understand what was wrong in my code, I finally started to play with the macro, and checked wether returning an i32 instead of the PamError enum is changing anything.

And sundenly, it worked! I don't know why, as I still have a lot to learn in rust, but now everything works fine.

```rust
#[no_mangle]
#[doc(hidden)]
pub unsafe extern "C" fn pam_sm_authenticate(pamh: pamsm::Pam, flags: i32, argc: usize, argv: *const *const u8) -> i32 {
    use std::ffi::CStr;
    use std::os::raw::c_char;

    let mut args = Vec::<String>::with_capacity(argc);
    for count in 0..(argc as isize) {
        match { CStr::from_ptr(*argv.offset(count) as *const c_char).to_str() } {
            Ok(s) => args.push(s.to_owned()),
            Err(_) => return pamsm::PamError::SERVICE_ERR as i32,
        };
    }
    PamSafe::authenticate(pamh, PamFlags::from_bits_unchecked(flags), args) as i32
}
```

I finally rewrote the pam_module macro to return i32 and put it back into the full project, and now everything works as expected!

**4. Ideas...**

A few ideas from what I see on cargo build:
- a problem in conversion from PamError to i32 when used in C
- `extern` fn uses type `PamError`, which is not FFI-safe - on pamsm::PamError result, but from what I read, this is related to thread-safety and not result conversion

**Comment by momiji** [comment]
I forgot to tell I'm using near latest rust version.

```sh
$ cargo version
cargo 1.60.0 (d1fd9fe 2022-03-01)
```

**Comment by rcatolino** [comment]
I believe you're right, rust makes no guarantee on the memory representation of the PamError enum so we can't just return the variants and expect them to have the right size. It must have been working by pure luck so far.

However I think we should to cast the variants as c_int and not i32 or it'll break on platforms where the c int is not 32 bit. (Are there platforms like that out there ?)
I did a quick try like that : 
```rust
macro_rules! pam_callback {
            ($pam_cb:ident, $rust_cb:ident) => {
                #[no_mangle]
                #[doc(hidden)]
                use std::os::raw::c_int;
                pub unsafe extern "C" fn $pam_cb(
                    pamh: pamsm::Pam,
                    flags: i32,
                    argc: usize,
                    argv: *const *const u8,
                ) -> c_int {
                    use std::ffi::CStr;
                    use std::os::raw::c_char;

                    let mut args = Vec::<String>::with_capacity(argc);
                    for count in 0..(argc as isize) {
                        match { CStr::from_ptr(*argv.offset(count) as *const c_char).to_str() } {
                            Ok(s) => args.push(s.to_owned()),
                            Err(_) => return pamsm::PamError::SERVICE_ERR as c_int,
                        };
                    }
                    <$pamsm_ty>::$rust_cb(pamh, PamFlags::from_bits_unchecked(flags), args) as c_int
                }
            };
        }
```
But it breaks if the pam module also imports `std::os::raw::c_int` :(
I'll try to think of something and patch this later. Or if you find how to import `use std::os::raw::c_int;` in the macro without breaking the users, feel free to send a pr.

**Comment by momiji** [comment]
Good news, I didn't knew about the c_int thing, I did a fast google search and indeed it is always i32=c_int, expect on esoteric systems :)

Does it mean the method signature should be globally changed to (flags: c_int, argc c_int), unless there is an alignment issue ?
Otherwise, maybe using i32 like in flags temporarily can work?

**Comment by momiji** [comment]
Indeed, adding the use breaks everything, especially when more than one callback is used, like I do in my project!

```rust
46 |                 use std::os::raw::c_int;
   |                     ^^^^^^^^^^^^^^^^^^^
   |                     |
   |                     `c_int` reimported here
   |                     previous import of the type `c_int` here
```

However, it looks like the following builds, but I haven't tested if it really works. And we still need to change flags and argc types...

```rust
        macro_rules! pam_callback {
            ($pam_cb:ident, $rust_cb:ident) => {
                #[no_mangle]
                #[doc(hidden)]
                pub unsafe extern "C" fn $pam_cb(
                    pamh: pamsm::Pam,
                    flags: i32,
                    argc: usize,
                    argv: *const *const u8,
                ) -> std::os::raw::c_int {
                    use std::ffi::CStr;
                    use std::os::raw::c_char;
                    use std::os::raw::c_int;

                    let mut args = Vec::<String>::with_capacity(argc);
                    for count in 0..(argc as isize) {
                        match { CStr::from_ptr(*argv.offset(count) as *const c_char).to_str() } {
                            Ok(s) => args.push(s.to_owned()),
                            Err(_) => return pamsm::PamError::SERVICE_ERR as c_int
                        };
                    }
                    <$pamsm_ty>::$rust_cb(pamh, PamFlags::from_bits_unchecked(flags), args) as c_int
                }
            };
        }
```

**Comment by rcatolino** [comment]
You're right those integer types are all wrong, especially `argc: usize` which should be 64bits on x64 ??. Actually I don't even understand how this is working when the pam users are expecting a 32 bit sized int...

**Comment by rcatolino** [comment]
Yeah I think using inline `std::os::raw::c_int` is the best way to do this, just have to use that everywhere the corresponding pam signature uses `int`

**Comment by rcatolino** [comment]
I've committed a new callback using `std::os::raw::c_int` everywhere. The test module seems to be working. But I still need to think about all the types/casts before releasing a something.
Can you try if it works on your end with the new code ?

**Comment by momiji** [comment]
Sure, I'll try do do it tomorrow - it's near midnight here...
My tests will be done on rhel 7 and 8, x64 for both.
I checked the pam_*.h to find the real signature, and it just show "int".

**Comment by lucab** [comment]
I may be missing something here, but it feels like the underlying problem may possibly be that `PamError` lacks an explicit `repr(int)` (see [docs](https://doc.rust-lang.org/nomicon/other-reprs.html#alternative-representations)).
There is also an implicit `int` vs `i32` mismatch which is hidden behind the `i32_enum` macro. It should really be a `int_enum` one instead, or simply dropped as it is used only once (then writing the enum directly).

**Comment by momiji** [comment]
Hello,

I finally got the time to do the tests, and it works now with this code, which is quite the same as the commited one, which addition c_char.

```rust
        macro_rules! pam_callback {
            ($pam_cb:ident, $rust_cb:ident) => {
                #[no_mangle]
                #[doc(hidden)]
                pub unsafe extern "C" fn $pam_cb(
                    pamh: pamsm::Pam,
                    flags: std::os::raw::c_int,
                    argc: std::os::raw::c_int,
                    argv: *const *const std::os::raw::c_char,
                ) -> std::os::raw::c_int {
                    use std::ffi::CStr;
                    use std::os::raw::c_int;

                    let mut args = Vec::<String>::with_capacity(argc as usize);
                    for count in 0..(argc as isize) {
                        match { CStr::from_ptr(*argv.offset(count)).to_str() } {
                            Ok(s) => args.push(s.to_owned()),
                            Err(_) => return pamsm::PamError::SERVICE_ERR as c_int
                        };
                    }
                    <$pamsm_ty>::$rust_cb(pamh, PamFlags::from_bits_unchecked(flags), args) as c_int
                }
            };
       }
```

I tried @lucab's idea to add the repr(c_int) to the enum but it does not add any converter. It may be possible to add the converter to the associated impl, it's just that I don't know how to do it and I feel it is not necessary as long as the conversion is 
 done in the macro. But it is a good idea and a new thing I learned by reading the docs, thx!

It also look like we need to add this repr(C) to the Pam structure, as it generates a warning on being not FFI compliant.
I also tried it and it worked.

```rust
#[repr(C)]
pub struct Pam(pub(crate) PamHandle);
```

**Comment by rcatolino** [comment]
Ok, here are my thoughts
## Rust functions exported to external code
They have to match the expected pam prototype exactly. As far as I can tell this is only include the pam callbacks, which arguments are :
- `pamh : pamsm::Pam` 
- `flags : c_int`
- `argc : c_int`
- `argv : *const *const c_char`
and the return type :
- `c_int`
 
`pamsm::Pam` is an alias for a pointer (`*const c_uint`) that isn't used in the rust code, but only forwarded to the pam helper functions. I guess we can add a `repr(C)` here to satisfy the linter.

All of those types have the same size as the external code, so I believe we're good here.

However I'd rather use the 'natural' types for rust (`ui32/i32/i64/ui64/isize/usize` for ints, `String` for text and `CString` for array of bytes). So the job of the callback wrapper is to do the expected conversions, which are :
- `flags : c_int` to `flags : i32` I don't think this can overflow because if pam defines flags that don't fit in 32 bits it will break virtually all platforms out there. However we might as well change PamFlags to use c_int since it doesn't impact the rest of the code
- `argc : c_int` to `argc : isize` and `argc: usize` This may overflow if we have a platform with 32 bits pointers and 64 bits `int`, but I'd be surprised if such a platform exists and is supported by pam. However an underflow check wouldn't hurt.
- `argv :**c_char` to `argv : Vec<String>` The conversion is handled by [`CStr::to_str`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.to_str) and we return SERVICE_ERR if an argument is not valid utf8.
- `PamError` to `c_int` for the return type. The biggest value for pam error is 31, so this won't overflow (And if we ever add an error value that doesn't fit in 32bits, the cast will cause a compile error). Since we don't' directly send `PamError` as a return value, but we explicitly cast it to a `c_int` I don't think we need to add `repr(C)` to this enum.

## External functions called from rust
Those are all the `extern "C"` functions declared in `libpam.rs`.
As far as I can see the only structs/enums exchanged with external code are `PamConv` and related `PamMessage`, `PamResponse` which have the required `repr(C)` 
I've took a quick glance at the conversions going on there and didn't see anything too crazy.
However as @lucab pointed out, we are converting all of the return values to `i32` when calling `PamError::new()`, we might as well use `c_int` in the macro and remove int conversions.

@lucab I'd rather keep the `PamError` macro as it prevents adding variants to the enum and forgetting to add the corresponding match branch.
