### ISSUE TITLE
No changelog, and API breakage between 0.4 and 0.5

### ISSUE THREAD

**Issue by Natureshadow** [rcatolino/pam_sm_rust#29]
Trying to update `pamsm` from 0.4 to 0.5, I get the following error:

```plain
33 | use pamsm::{PamServiceModule, Pam, PamFlag, PamError, PamLibExt};
   |                                    ^^^^^^^
   |                                    |
   |                                    no `PamFlag` in the root
   |                                    help: a similar name exists in the module: `PamFlags`
error[E0433]: failed to resolve: use of undeclared type `PamFlags`
```

Seems pretty easy to fix, but trying to find out documentation on the change, I discovered that this project is missing a changelog.

https://keepachangelog.com/en/1.0.0/

**Comment by lucab** [comment]
The API breakage is intended and correct, 0.4 and 0.5 are not semver-compatible.

For the full list of changes, see <https://github.com/rcatolino/pam_sm_rust/compare/0.4.3...0.5.0>.

**Comment by lucab** [comment]
@rcatolino slightly related to this, I think you forgot to push the tags for `0.5.1` and `0.5.2`. If you have those locally already, can you push them too? Thanks!

**Comment by Natureshadow** [comment]
> The API breakage is intended and correct, 0.4 and 0.5 are not semver-compatible.

That does not explain the absence of a reasonably written changelog.
